### ISSUE TITLE
server rendering

### ISSUE THREAD

**Issue by revolunet** [vvo/in-viewport#18]
Hi !

I have an issue when pre-rendering pages from server when using `in-viewport`. classic access to unknow `global.document`. i fixed quickly here https://github.com/revolunet/in-viewport/commit/57e5db365aee600af91d7164313b7355ff9f456b tell me if you want a PR

Cheers and thanks for that nice lib :)

**Comment by tzi** [comment]
Seems great for me!
A PR would be nice :)

**Comment by vvo** [comment]
Do you use the in-viewport feature server side? I wonder how it works :D If you do not use it then maybe you can try to not include it.

Other than that I think an easier fix might be to make contains a function declaration rather than a variable like that. So that the code is only executed when relevant.

Also did you see https://github.com/camwiegert/in-view? At some point I might depreciate this is https://github.com/camwiegert/in-view goes well. They are basically adding features from in-viewport

**Comment by revolunet** [comment]
Thanks for the feedback !

i'm playing with the great phenomic.io and it prerenders all pages and breaks on every browser-only lib

thanks for `in-view` looks nice, will try

**Comment by vvo** [comment]
> Other than that I think an easier fix might be to make contains a function declaration rather than a variable like that. So that the code is only executed when relevant.

Can you do that instead? Would be better I think

**Comment by revolunet** [comment]
yep its better :)

i have some trouble running the saucelabs tests though..

**Comment by vvo** [comment]
> i have some trouble running the saucelabs tests though..

No big deal, they are somehow broken that's ok. Your change should be OK
